name: "GitHub Action for Firebase"
author: "Jeremy Shore"
description: "Wraps the firebase-tools CLI to enable common commands."

branding:
  icon: "package"
  color: "gray-dark"

outputs:
  response:
    description: "Response from the firebase command executed"

runs:
  using: "docker"
  image: "docker://w9jds/firebase-action:v15.25.0@sha256:4824ef6f2a6c6bf1e432897f7e12b317597645aeaec4fe61607f6081105a1d4a"
