name: "GitHub Action for Firebase"
author: "Jeremy Shore"
description: "Wraps the firebase-tools CLI to enable common commands."

branding:
  icon: "package"
  color: "gray-dark"

outputs:
  response:
    description: "Response from the firebase command executed"

runs:
  using: "docker"
  image: "docker://w9jds/firebase-action@sha256:634ae5b502d9c462d6e86012270a569a698a7ecec7729836e8566f4cd23d9c37" # v15.23.0
